[template]
src = "helloworld_http.conf.tmpl"
dest = "/etc/nginx/conf.d/helloworld_http.conf"
keys = [
    "/cluster_alpha/helloworld_http",
]

owner = "root"
mode = "0644"

check_cmd = "/usr/sbin/nginx -t"
reload_cmd = "kill -HUP $(cat /var/run/nginx/nginx.pid)"
