[template]
src = "helloworld.conf.tmpl"
dest = "/etc/nginx/conf.d/hello-80_discovered_via_etcd.conf"
keys = [
    "/cluster_alpha/hello-80",
]

owner = "root"
mode = "0644"

check_cmd = "/usr/sbin/nginx -t"
reload_cmd = "kill -HUP $(cat /var/run/nginx/nginx.pid)"

